// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20201029004923_MigracionEditorial")]
    partial class MigracionEditorial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Editorial", b =>
                {
                    b.Property<Guid>("IdEditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("IdEditoria");

                    b.ToTable("Editorial");

                    b.HasData(
                        new
                        {
                            IdEditoria = new Guid("1af92554-5333-423a-8b06-f2530e72a03f"),
                            Nombre = "Almadía"
                        },
                        new
                        {
                            IdEditoria = new Guid("d960a3b3-e2e8-4d9c-b54a-0e06289c4c0d"),
                            Nombre = "Acantilado"
                        },
                        new
                        {
                            IdEditoria = new Guid("c12e9cfe-615e-4ee5-86a6-19bc01505ca6"),
                            Nombre = "Aguilar"
                        },
                        new
                        {
                            IdEditoria = new Guid("e973c79a-e444-482d-96a4-ee92c073f990"),
                            Nombre = "Akal"
                        },
                        new
                        {
                            IdEditoria = new Guid("c7d99b55-c0d0-41e6-abb9-635b35fd4e6f"),
                            Nombre = "Alba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
