// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20201029012545_MigracionLibro")]
    partial class MigracionLibro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Editorial", b =>
                {
                    b.Property<Guid>("IdEditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("IdEditoria");

                    b.ToTable("Editorial");

                    b.HasData(
                        new
                        {
                            IdEditoria = new Guid("7e072a51-1b2a-4a68-afa2-dc416f2eb2a8"),
                            Nombre = "Almadía"
                        },
                        new
                        {
                            IdEditoria = new Guid("fab3257e-fecb-490a-9f28-830b8cf71a19"),
                            Nombre = "Acantilado"
                        },
                        new
                        {
                            IdEditoria = new Guid("614e15cc-9fd0-43bd-aa61-c87ff869250d"),
                            Nombre = "Aguilar"
                        },
                        new
                        {
                            IdEditoria = new Guid("2abf04b4-c6ab-4646-a2f3-c77600eb586f"),
                            Nombre = "Akal"
                        },
                        new
                        {
                            IdEditoria = new Guid("2c75655c-6b7f-4e5a-aa24-d8b0db8ab239"),
                            Nombre = "Alba"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Libro", b =>
                {
                    b.Property<Guid>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdEditoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("IdLibro");

                    b.ToTable("Libro");
                });
#pragma warning restore 612, 618
        }
    }
}
