// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(WebApiContext))]
    partial class WebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Editorial", b =>
                {
                    b.Property<Guid>("IdEditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("IdEditoria");

                    b.ToTable("Editorial");

                    b.HasData(
                        new
                        {
                            IdEditoria = new Guid("271cced2-6437-424c-8a1a-fa3988e2ae24"),
                            Nombre = "Almadía"
                        },
                        new
                        {
                            IdEditoria = new Guid("9f30d4ce-bf1f-4964-be63-2036a4738764"),
                            Nombre = "Acantilado"
                        },
                        new
                        {
                            IdEditoria = new Guid("cf9e0c41-2605-4821-8c62-228491d14a3d"),
                            Nombre = "Aguilar"
                        },
                        new
                        {
                            IdEditoria = new Guid("5256401b-e0f4-44ad-9be3-18fccdae0aff"),
                            Nombre = "Akal"
                        },
                        new
                        {
                            IdEditoria = new Guid("fcf8403f-8b37-4ffa-95bc-162b07694847"),
                            Nombre = "Alba"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Libro", b =>
                {
                    b.Property<Guid>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdEditoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("IdLibro");

                    b.ToTable("Libro");
                });
#pragma warning restore 612, 618
        }
    }
}
